import Foundation

let t = TestRunner()
print("eureka-tests")

smokeTests(t)
taskStoreTests(t)
decoderTests(t)
spoolConsumerTests(t)
installerTests(t)
geometryTests(t)
cardQueueTests(t)
codexNotifyInstallerTests(t)
codexRolloutTests(t)
errorSnifferTests(t)
contextEstimatorTests(t)
sessionBootstrapTests(t)
transcriptWatcherTests(t)
projectResolverTests(t)
sessionIndexerTests(t)
deduplicatorTests(t)
claudeScannerTests(t)
codexScannerTests(t)
pricingTests(t)
aggregatorTests(t)
rateLimitTests(t)

t.finish()
